#!/usr/bin/env python3
"""
RapidMastery 学习记录导出脚本
自动保存学习笔记到 study-notes/ 并推送到远程仓库
"""

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def sanitize_filename(name: str) -> str:
    """将主题名转换为安全的文件名"""
    # 替换不安全字符为连字符
    name = re.sub(r'[^\w\s-]', '', name)
    name = re.sub(r'[-\s]+', '-', name)
    return name.lower().strip('-')


def generate_filename(topic: str) -> str:
    """生成文件名：YYYY-MM-DD-topic.md"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    safe_topic = sanitize_filename(topic)
    return f"{date_str}-{safe_topic}.md"


def generate_commit_message(topic: str) -> str:
    """生成提交信息：[主题] 学习记录 - YYYY-MM-DD"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    return f"[{topic}] 学习记录 - {date_str}"


def ensure_study_notes_dir() -> Path:
    """确保 study-notes 目录存在"""
    # 从脚本位置向上查找项目根目录
    script_dir = Path(__file__).parent.parent.parent
    study_notes_dir = script_dir / 'study-notes'
    study_notes_dir.mkdir(exist_ok=True)
    return study_notes_dir


def create_learning_note(topic: str, content: str, depth: str = "apply") -> Path:
    """创建学习笔记文件"""
    study_notes_dir = ensure_study_notes_dir()
    filename = generate_filename(topic)
    filepath = study_notes_dir / filename
    
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    template = f"""# {topic}

**学习时间**: {now}  
**目标深度**: {depth}  
**掌握程度**: ⭐⭐⭐☆☆

---

## 核心概念

<!-- 填写 RapidMastery 生成的核心概念树 -->

## 费曼讲解记录

**我的理解**：

**追问要点**：

## 刻意练习

**完成的练习**：

**薄弱点**：

## 复习计划

- [ ] 1天后：
- [ ] 3天后：
- [ ] 7天后：
- [ ] 30天后：

---

## 原始对话摘录

<details>
<summary>展开查看完整对话</summary>

{content}

</details>

---

*Generated by RapidMastery Exporter*
"""
    
    filepath.write_text(template, encoding='utf-8')
    print(f"[OK] 已创建学习笔记: {filepath}")
    return filepath


def update_readme_index(study_notes_dir: Path) -> None:
    """更新 README.md 索引文件"""
    readme_path = study_notes_dir / 'README.md'
    
    # 获取所有笔记文件
    notes = sorted(study_notes_dir.glob('*.md'))
    notes = [n for n in notes if n.name != 'README.md']
    
    content = """# 📚 学习笔记索引

本目录保存所有 RapidMastery 学习记录。

## 快速统计

| 指标 | 数值 |
|------|------|
"""
    content += f"| 总笔记数 | {len(notes)} |\n"
    content += f"| 最后更新 | {datetime.now().strftime('%Y-%m-%d')} |\n\n"
    
    content += "## 笔记列表\n\n"
    content += "| 日期 | 主题 | 文件 |\n"
    content += "|------|------|------|\n"
    
    for note in notes:
        # 从文件名提取日期和主题
        parts = note.stem.split('-', 3)
        if len(parts) >= 4:
            date = f"{parts[0]}-{parts[1]}-{parts[2]}"
            topic = parts[3].replace('-', ' ').title()
        else:
            date = note.stem[:10] if len(note.stem) >= 10 else "未知"
            topic = note.stem.title()
        
        content += f"| {date} | {topic} | [{note.name}]({note.name}) |\n"
    
    content += """
---

*自动生成于 {}*
""".format(datetime.now().strftime('%Y-%m-%d %H:%M'))
    
    readme_path.write_text(content, encoding='utf-8')
    print(f"[OK] 已更新索引: {readme_path}")


def git_commit_and_push(filepath: Path, topic: str) -> bool:
    """执行 git add/commit/push"""
    try:
        # 获取项目根目录
        project_root = filepath.parent.parent
        
        # git add
        subprocess.run(
            ['git', 'add', str(filepath), str(filepath.parent / 'README.md')],
            cwd=project_root,
            check=True,
            capture_output=True,
            text=True
        )
        print(f"[OK] Git add 完成")
        
        # git commit
        commit_msg = generate_commit_message(topic)
        result = subprocess.run(
            ['git', 'commit', '-m', commit_msg],
            cwd=project_root,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print(f"[OK] Git commit: {commit_msg}")
        elif "nothing to commit" in result.stdout or "nothing to commit" in result.stderr:
            print("[INFO] 没有变更需要提交")
            return True
        else:
            print(f"[WARN] Git commit 输出: {result.stdout or result.stderr}")
        
        # git push
        result = subprocess.run(
            ['git', 'push', 'origin', 'HEAD'],
            cwd=project_root,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("[OK] Git push 成功")
            return True
        else:
            print(f"[ERROR] Git push 失败: {result.stderr}")
            return False
            
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Git 操作失败: {e}")
        print(f"       输出: {e.stdout or e.stderr}")
        return False
    except FileNotFoundError:
        print("[ERROR] 未找到 git 命令，请确保 git 已安装并添加到 PATH")
        return False


def push_only() -> bool:
    """仅执行 git push"""
    try:
        script_dir = Path(__file__).parent.parent.parent
        
        # 检查是否有未提交的更改
        status = subprocess.run(
            ['git', 'status', '--porcelain'],
            cwd=script_dir,
            capture_output=True,
            text=True
        )
        
        if status.stdout.strip():
            print("[WARN] 有未提交的更改，请先提交:")
            print(status.stdout)
            return False
        
        # git push
        result = subprocess.run(
            ['git', 'push', 'origin', 'HEAD'],
            cwd=script_dir,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("✅ Git push 成功")
            return True
        else:
            print(f"❌ Git push 失败: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"[ERROR] 错误: {e}")
        return False


def commit_all() -> bool:
    """提交所有未提交的笔记"""
    try:
        script_dir = Path(__file__).parent.parent.parent
        
        # git add all
        subprocess.run(
            ['git', 'add', 'study-notes/'],
            cwd=script_dir,
            check=True,
            capture_output=True,
            text=True
        )
        
        # git commit
        date_str = datetime.now().strftime('%Y-%m-%d')
        commit_msg = f"批量更新学习笔记 - {date_str}"
        
        result = subprocess.run(
            ['git', 'commit', '-m', commit_msg],
            cwd=script_dir,
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print(f"✅ Git commit: {commit_msg}")
        elif "nothing to commit" in result.stdout or "nothing to commit" in result.stderr:
            print("ℹ️ 没有变更需要提交")
            return True
        else:
            print(f"⚠️ {result.stdout or result.stderr}")
            return False
        
        # git push
        result = subprocess.run(
            ['git', 'push', 'origin', 'HEAD'],
            cwd=script_dir,
            check=True,
            capture_output=True,
            text=True
        )
        
        print("✅ Git push 成功")
        return True
        
    except Exception as e:
        print(f"❌ 错误: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description='RapidMastery 学习记录导出工具'
    )
    parser.add_argument(
        '--topic', '-t',
        help='学习主题名称'
    )
    parser.add_argument(
        '--content', '-c',
        help='学习内容（支持 Markdown）'
    )
    parser.add_argument(
        '--depth', '-d',
        default='apply',
        choices=['know', 'apply', 'teach', 'master'],
        help='目标深度 (默认: apply)'
    )
    parser.add_argument(
        '--push-only',
        action='store_true',
        help='仅执行 git push'
    )
    parser.add_argument(
        '--commit-all',
        action='store_true',
        help='提交所有未提交的笔记'
    )
    parser.add_argument(
        '--no-push',
        action='store_true',
        help='不执行 git push'
    )
    
    args = parser.parse_args()
    
    if args.push_only:
        success = push_only()
        sys.exit(0 if success else 1)
    
    if args.commit_all:
        success = commit_all()
        sys.exit(0 if success else 1)
    
    if not args.topic:
        print("[ERROR] 请提供主题名称: --topic \"主题名\"")
        sys.exit(1)
    
    # 创建学习笔记
    content = args.content or "<!-- 请粘贴 RapidMastery 对话内容 -->"
    filepath = create_learning_note(args.topic, content, args.depth)
    
    # 更新索引
    update_readme_index(filepath.parent)
    
    # Git 操作
    if not args.no_push:
        print("\n[START] 开始 Git 操作...")
        git_commit_and_push(filepath, args.topic)
    
    print(f"\n[DONE] 完成！学习笔记已保存到: {filepath}")


if __name__ == '__main__':
    main()
